//  use this quizData in your app.
export const quizData = [{
    "question": "Which language runs in a web browser?",
    "a": "Java",
    "b": "C",
    "c": "Python",
    "d": "JavaScript",
    "correct": "d",
},
{
    "question": "What does CSS stand for?",
    "a": "Central Style Sheets",
    "b": "Cascading Style Sheets",
    "c": "Cascading Simple Sheets",
    "d": "Cars SUVs Sailboats",
    "correct": "b",
},
{
    "question": "What does HTML stand for?",
    "a": "Hypertext Markup Language",
    "b": "Hypertext Markdown Language",
    "c": "Hyperloop Machine Language",
    "d": "Helicopters Terminals Motorboats Lamborginis",
    "correct": "a",
},
{
    "question": "What year was JavaScript launched?",
    "a": "1996",
    "b": "1995",
    "c": "1994",
    "d": "none of the above",
    "correct": "b",
}, {
    "question": "Which of the following is a JavaScript framework?",
    "a": "Django",
    "b": "Laravel",
    "c": "React",
    "d": "Flask",
    "correct": "c",
},
{
    "question": "Which tag is used to create a hyperlink in HTML?",
    "a": "<link>",
    "b": "<a>",
    "c": "<href>",
    "d": "<hyper>",
    "correct": "b",
},
{
    "question": "Which property is used to change the background color in CSS?",
    "a": "color",
    "b": "bgcolor",
    "c": "background-color",
    "d": "background",
    "correct": "c",
},
{
    "question": "Inside which HTML element do we put the JavaScript?",
    "a": "<script>",
    "b": "<javascript>",
    "c": "<js>",
    "d": "<code>",
    "correct": "a",
},
{
    "question": "Which of the following is NOT a programming language?",
    "a": "Python",
    "b": "Ruby",
    "c": "HTML",
    "d": "C++",
    "correct": "c",
},
{
    "question": "Which company developed JavaScript?",
    "a": "Google",
    "b": "Netscape",
    "c": "Microsoft",
    "d": "Apple",
    "correct": "b",
}
    // you can add more quiz here
]